export const easyQuestions = [
  "Hi, baby. Who’s available?",
  "Hi, send photos",
  "Hi, who’s on the menu?",
  "Hey, who’s new?",
  "Hello, dear. Who’s here?",
  "Hi, babe. Send photos",
  "Send photos.",
  "Who’s new",
  "Who’s available?",
  "Hi, who’s available now?",
  "How much?",
  "How much is one shot?",
  "How much 1hr?",
  "Price",
  "What are your rates?",
  "What’s the rate?",
  "What’s your rate?",
  "How much 2 shots?",
  "How much 30min?",
  "What’s the rate for 1hr?",
  "What’s golden shower?",
  "How much is COF?",
  "Can I cum inside?",
  "How much is anal?",
  "What’s the rate for CIM?",
  "What’s the price for COB?",
  "What is infall?",
  "What is outcall?",
  "Where do you live?",
  "Where is your location?",
  "Send location",
  "What’s the address?",
  "Address",
];

export const mediumQuestions = [
  "How much 1hr with CIM?",
  "How much 2hrs?",
  "What’s the price for 3hrs?",
  "What’s the rate for 1hr with anal?",
  "How much for 1hr if we come together?",
  "How much is full night?",
  "What’s the difference between lesbian and duo?",
  "Can I pay by card?",
  "Can I pay by PayPal?",
  "I have 1000. What can I get for this price?",
  "I have 700. Can I come?",
  "I have 500. Can I come?",
  "I have 1300. Send me a girl for 1hr.",
  "How much is 45 min incall?",
  "How much is 45 min outcall?",
];

export const hardQuestions = [
  "How much 2hrs with lesbian show?",
  "How much is 1h30min?",
  "How much is 5hrs with COB and anal?",
  "How much 2hrs with lesbian and anal for both girls?",
  "How much 3hrs duo with French kiss, pussy licking and squirt?",
  "How much is mistress for 1hr?",
  "How much if I spit on her, choke her, slap and spank her? 3hrs my place",
];

export const testQuestions = [
  "Hi, baby. Who’s available?",
  "Hi, send photos",
  "Hi, who’s on the menu?",
  "Hey, who’s new?",
  "Hello, dear. Who’s here?",
  "Hi, babe. Send photos",
  "Send photos.",
  "Who’s new",
  "Who’s available?",
  "Hi, who’s available now?",
  "How much?",
  "How much is one shot?",
  "How much 1hr?",
  "Price",
  "What are your rates?",
  "What’s the rate?",
  "What’s your rate?",
  "How much 2 shots?",
  "How much 30min?",
  "What’s the rate for 1hr?",
  "What’s golden shower?",
  "How much is COF?",
  "Can I cum inside?",
  "How much is anal?",
  "What’s the rate for CIM?",
  "What’s the price for COB?",
  "What is inсall?",
  "What is outcall?",
  "Where do you live?",
  "Where is your location?",
  "Send location",
  "What’s the address?",
  "Address",
  "How much 1hr with CIM?",
  "How much 2hrs?",
  "What’s the price for 3hrs?",
  "What’s the rate for 1hr with anal?",
  "How much for 1hr if we come together?",
  "How much is full night?",
  "What’s the difference between lesbian and duo?",
  "Can I pay by card?",
  "Can I pay by PayPal?",
  "I have 1000. What can I get for this price?",
  "I have 700. Can I come?",
  "I have 500. Can I come?",
  "I have 1300. Send me a girl for 1hr.",
  "How much is 45 min incall?",
  "How much is 45 min outcall?",
  "What is included in standard service?",
  "How much 2hrs with lesbian show?",
  "How much is 1h30min?",
  "How much is 5hrs with COB and anal?",
  "How much 2hrs with lesbian and anal for both girls?",
  "How much 3hrs duo with French kiss, pussy licking and squirt?",
  "How much is mistress for 1hr?",
  "How much if I spit on her, choke her, slap and spank her? 3hrs my place",
];
